version: "3.7"

services:

  postgres14:
    platform: linux/amd64
    image: timescale/timescaledb:2.8.1-pg14
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5434:5432

